# Generated by Django 2.2 on 2019-04-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameteamplayer',
            name='mu',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='gameteamplayer',
            name='sigma',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
