# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('name', models.SlugField(primary_key=True, serialize=False)),
                ('mu', models.FloatField(default=25.0)),
                ('sigma', models.FloatField(default=8.333333333333334)),
                ('beta', models.FloatField(default=4.166666666666667)),
                ('tau', models.FloatField(default=0.08333333333333334)),
                ('draw_probability', models.FloatField(default=0.1)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.SlugField()),
                ('print_name', models.CharField(max_length=255)),
                ('mu', models.FloatField()),
                ('sigma', models.FloatField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='skillboards.Board')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set([('username', 'board')]),
        ),
        migrations.AlterIndexTogether(
            name='player',
            index_together=set([('username', 'board')]),
        ),
    ]
