# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skillboards', '0002_auto_20170520_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartialGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.SmallIntegerField(choices=[(1, 'solo'), (2, 'team')])),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('board', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='skillboards.Board')),
            ],
        ),
        migrations.CreateModel(
            name='PartialGamePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.BooleanField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_info', to='skillboards.PartialGame')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='games',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partialgameplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skillboards.Player'),
        ),
        migrations.AlterUniqueTogether(
            name='partialgameplayer',
            unique_together=set([('game', 'player')]),
        ),
        migrations.AlterIndexTogether(
            name='partialgameplayer',
            index_together=set([('game', 'player')]),
        ),
    ]
