# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillboards', '0004_game_gameteam_gameteamplayer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameteamplayer',
            unique_together=set([('team', 'player')]),
        ),
        migrations.AlterIndexTogether(
            name='gameteamplayer',
            index_together=set([('team', 'player')]),
        ),
    ]
