# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skillboards', '0006_auto_20170525_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(db_index=True)),
                ('end', models.DateTimeField(db_index=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='skillboards.Board')),
            ],
        ),
    ]
