# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillboards', '0007_boardlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
