# Generated by Django 2.0 on 2018-01-27 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skillboards', '0010_auto_20170604_0326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='print_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='game',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='skillboards.Board'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='player',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='player',
            name='games',
        ),
        migrations.RemoveField(
            model_name='player',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='player',
            name='username',
        ),
        migrations.RemoveField(
            model_name='player',
            name='wins',
        ),
    ]
