# Generated by Django 2.0 on 2018-01-28 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillboards', '0011_auto_20180127_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='disabled',
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('board', 'name')},
        ),
        migrations.AlterIndexTogether(
            name='player',
            index_together={('board', 'name')},
        ),
    ]
