# Generated by Django 2.0 on 2018-02-08 03:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillboards', '0012_auto_20180128_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={},
        ),
        migrations.AddField(
            model_name='board',
            name='max_players',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='board',
            name='max_teams',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='gameteamplayer',
            name='weight',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
