# Generated by Django 2.0 on 2018-02-18 01:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillboards', '0013_auto_20180208_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='min_players',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='board',
            name='draw_probability',
            field=models.FloatField(default=0.1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
